### PR TITLE
debug

### PR DESCRIPTION
**Pull request by dokspy**

### CODE REVIEW

**Comment by amarsik1** [comment]
dont correct realization in
`<div class="zaglyshka"></div>` to `class="dummy"></div>`
use flexbox or grid

**Comment by dokspy** [comment]
ok

**Comment by VadymSula** [comment]
This open pul-request is useless. You must to merge your branch "django_cv" into master!

**Comment by VadymSula** [comment]
Please, use correct name for commits (debUg*)

**Pull request merged**
